<?php


/**
 * Skeleton subclass for representing a row from the 'queue' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/21/15 17:44:48
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Queue extends BaseQueue {

} // Queue
