<?php


/**
 * Skeleton subclass for performing query and update operations on the 'video' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/07/15 13:54:43
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VideoPeer extends BaseVideoPeer {
    
    public static function getInfo($id)
    {
        $video = VideoPeer::retrieveByPk($id);
        
        $arInfo = array(
            "name" => $video->getName(),
            "width" => $video->getWidth(),
            "height" => $video->getHeight(),
            "video_bitrate" => $video->getVideoBitrate(),
            "audio_bitrate" => $video->getAudioBitrate()
        );
        return $arInfo;
    }
        
} // VideoPeer
