<?php


/**
 * Skeleton subclass for performing query and update operations on the 'video_link' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/21/15 17:44:49
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VideoLinkPeer extends BaseVideoLinkPeer {
    
    public static function AddLink(Video $original, Video $converted)
    {
        $link = new VideoLink;
        $link->setOriginal($original->getId());
        $link->setConverted($converted->getId());
        return $link->save();
    }

} // VideoLinkPeer
