propel:
  video:
    id: ~
    name: { type: varchar(255), required: true }
    width: { type: integer }
    height: { type: integer }
    video_bitrate: { type: float }
    audio_bitrate: { type: float }
    user_id: { type: integer, required: true }
    filename: { type: varchar(255) }
    created_at: ~
    updated_at: ~
  
  status:
    id: ~
    name: { type: varchar(255), required: true }
  
  queue:
    id: ~
    video_id: { type: integer, foreignTable: video, foreignReference: id, required: true, onDelete: CASCADE }
    status: { type: integer, foreignTable: status, foreignReference: id, required: true, onDelete: CASCADE }
  
  video_link:
    id: ~
    original: { type: integer, foreignTable: video, foreignReference: id, required: true, onDelete: CASCADE }
    converted: { type: integer, foreignTable: video, foreignReference: id, required: true, onDelete: CASCADE }
     