propel:
  video:
    id: ~
    name: { type: varchar(255), required: true }
    width: { type: integer }
    height: { type: integer }
    video_bitrate: { type: float }
    audio_bitrate: { type: float }
    user_id: { type: integer, required: true }
    filename: { type: varchar(255) }
    created_at: ~
    updated_at: ~