<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2015/05/13 22:34:15
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfmixer' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformfiltergenerator' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgenerateadmintask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoxmltask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sftesterpropel' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfwidgetformpropelchoice' => 'D:/my_projects/rest.local/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',

  // project
  'baseusersformfilter' => 'D:/my_projects/rest.local/lib/filter/base/BaseUsersFormFilter.class.php',
  'basevideoformfilter' => 'D:/my_projects/rest.local/lib/filter/base/BaseVideoFormFilter.class.php',
  'baseformfilterpropel' => 'D:/my_projects/rest.local/lib/filter/BaseFormFilterPropel.class.php',
  'usersformfilter' => 'D:/my_projects/rest.local/lib/filter/UsersFormFilter.class.php',
  'videoformfilter' => 'D:/my_projects/rest.local/lib/filter/VideoFormFilter.class.php',
  'baseusersform' => 'D:/my_projects/rest.local/lib/form/base/BaseUsersForm.class.php',
  'basevideoform' => 'D:/my_projects/rest.local/lib/form/base/BaseVideoForm.class.php',
  'baseform' => 'D:/my_projects/rest.local/lib/form/BaseForm.class.php',
  'baseformpropel' => 'D:/my_projects/rest.local/lib/form/BaseFormPropel.class.php',
  'uploadvideoform' => 'D:/my_projects/rest.local/lib/form/UploadVideoForm.class.php',
  'usersform' => 'D:/my_projects/rest.local/lib/form/UsersForm.class.php',
  'videoform' => 'D:/my_projects/rest.local/lib/form/VideoForm.class.php',

  // project_model
  'userstablemap' => 'D:/my_projects/rest.local/lib/model/map/UsersTableMap.php',
  'videotablemap' => 'D:/my_projects/rest.local/lib/model/map/VideoTableMap.php',
  'baseusers' => 'D:/my_projects/rest.local/lib/model/om/BaseUsers.php',
  'baseuserspeer' => 'D:/my_projects/rest.local/lib/model/om/BaseUsersPeer.php',
  'basevideo' => 'D:/my_projects/rest.local/lib/model/om/BaseVideo.php',
  'basevideopeer' => 'D:/my_projects/rest.local/lib/model/om/BaseVideoPeer.php',
  'users' => 'D:/my_projects/rest.local/lib/model/Users.php',
  'userspeer' => 'D:/my_projects/rest.local/lib/model/UsersPeer.php',
  'video' => 'D:/my_projects/rest.local/lib/model/Video.php',
  'videopeer' => 'D:/my_projects/rest.local/lib/model/VideoPeer.php',

  // application
  'myuser' => 'D:/my_projects/rest.local/apps/frontend/lib/myUser.class.php',

  // modules
);
