<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/05/14 11:20:31
sfConfig::add(array(
  'app_video_path' => 'D:\\my_projects\\rest.local\\web\\uploads/video/',
  'app_ffmpeg_path' => 'd:\\ffmpeg\\bin\\',
));
