<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/05/21 19:52:14
sfConfig::add(array(
  'app_video_path' => 'D:\\my_projects\\rest.local\\web\\uploads/video/',
  'app_ffmpeg_path' => 'd:\\ffmpeg\\bin\\',
  'app_mess_auth_required' => 'Authentification required',
  'app_mess_denied' => 'Access denied',
));
